### ISSUE TITLE
Cannot connect to host

### ISSUE THREAD

**Issue by xiaohanghang** [dmrz/baymax#1]
how to fix it:
`2018-03-02 18:05:12,521 DEBUG:baymax.bot: Getting updates...
2018-03-02 18:05:13,517 ERROR:baymax.bot: Polling cancelled
Traceback (most recent call last):
  File "/home/liuhang/.virtualenvs/baymax-master/lib/python3.6/site-packages/aiohttp/connector.py", line 797, in _wrap_create_connection
    return (yield from self._loop.create_connection(*args, **kwargs))
  File "uvloop/loop.pyx", line 1769, in create_connection
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liuhang/Desktop/baymax-master/baymax/bot.py", line 234, in start_polling
    async for update in self.update_generator():
  File "/home/liuhang/Desktop/baymax-master/baymax/bot.py", line 246, in update_generator
    updates = await self.get_updates()
  File "/home/liuhang/Desktop/baymax-master/baymax/bot.py", line 255, in get_updates
    response = await self.api.get_updates(self.timeout, self.update_id + 1)
  File "/home/liuhang/Desktop/baymax-master/baymax/api.py", line 43, in get_updates
    return await self.request(f'{self.base_url}/getUpdates', params=params)
  File "/home/liuhang/Desktop/baymax-master/baymax/api.py", line 33, in request
    url, data=payload, params=params, headers=headers) as resp:
  File "/home/liuhang/.virtualenvs/baymax-master/lib/python3.6/site-packages/aiohttp/client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "/home/liuhang/.virtualenvs/baymax-master/lib/python3.6/site-packages/aiohttp/client.py", line 267, in _request
    conn = yield from self._connector.connect(req)
  File "/home/liuhang/.virtualenvs/baymax-master/lib/python3.6/site-packages/aiohttp/connector.py", line 402, in connect
    proto = yield from self._create_connection(req)
  File "/home/liuhang/.virtualenvs/baymax-master/lib/python3.6/site-packages/aiohttp/connector.py", line 749, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/home/liuhang/.virtualenvs/baymax-master/lib/python3.6/site-packages/aiohttp/connector.py", line 860, in _create_direct_connection
    raise last_exc
  File "/home/liuhang/.virtualenvs/baymax-master/lib/python3.6/site-packages/aiohttp/connector.py", line 832, in _create_direct_connection
    req=req, client_error=client_error)
  File "/home/liuhang/.virtualenvs/baymax-master/lib/python3.6/site-packages/aiohttp/connector.py", line 804, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:True [Connection reset by peer]`

**Comment by dmrz** [comment]
Hi! Can you run the following command:

```bash
openssl s_client -connect api.telegram.org:443
```

And check it returns `Verify return code: 0 (ok)` in the end?

Also, can you show an example of your application code?

**Comment by xiaohanghang** [comment]
hello,I just browse your project from pycoder,I am a starter about asyn but  i am concerned about asyn,Can you make some tutorial about async and more detail descriptions about this project, thank you!!!

**Comment by xiaohanghang** [comment]
when i run openssl s_client -connect api.telegram.org:443,just `connect: Connection timed out
connect:errno=110
`

**Comment by dmrz** [comment]
Seems like there is a problem with your provider, maybe telegram api host is blocked or something. You can look for asyncio tutorials online. I am going to make documentation soon.

**Comment by dmrz** [comment]
You can also look [here](https://github.com/dmrz/baymax/blob/master/main.py) for bot usage examples.

**Comment by xiaohanghang** [comment]
Thanks a lot!!!
